CadastroDeClientes/Models/ClientesModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Components;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace CadastroDeClientes.Models
{
    public class ClientesModel
    { 
        //Data Annotations
        [Key]
        [Required]
        public int Id { get; set; }

        [Display(Name = "Nome do Cliente")]
        [Required(ErrorMessage = "O {0} é obrigatorio", AllowEmptyStrings = false)]
        [MinLength(3, ErrorMessage = "Nome inválido, informe no mínimo 3 caracteres")]
        [MaxLength(100, ErrorMessage = "Nome excedeu o tamanho permitido")]
        public string Nome { get; set; }

        [Display(Name = "CPF/CNPJ")]
        [Required(ErrorMessage = "O {0} é obrigatorio", AllowEmptyStrings = false)]
        [MaxLength(14, ErrorMessage = "CPF/CNPJ contém 11 digitos e CNPJ somente 14 digitos")]
        [Range(00000000000, 99999999999999)]
        public string Cpf { get; set; }

        
        [Display(Name = "Data de Nascimento", Description = "A idade deve ser acima de 18.")]
        [DataType(DataType.DateTime, ErrorMessage = "Data invalida")]
        [Required(ErrorMessage = "O {0} é obrigatorio", AllowEmptyStrings = false)]
        public DateTime? DataNascimento { get; set; }

        [Display(Name = "Tipo")]
        public int Tipo { get; set; }
        
        private int _contador;

        public Task Incremento(int incremento)
        {
            _contador += incremento;
            return Task.CompletedTask;
        }

        public Task<int> GetContador()
        {
            return Task.FromResult(_contador);
        }
    }
}

CadastroDeClientes/Models/ErrorViewModel.cs
using System;

namespace CadastroDeClientes.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

CadastroDeClientes/Controllers/ClientesController.cs
using CadastroDeClientes.Data;
using CadastroDeClientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;
using System.Data.SqlClient;
using System.Web.WebPages.Html;

namespace CadastroDeClientes.Controllers
{
    public class ClientesController : Controller
    {
        private readonly BancoContext _contexto;

        public ClientesController(BancoContext contexto)
        {
            _contexto = contexto;
        }
        public ActionResult Index(string Pesquisar = "")
        {

            var q = _contexto.Clientes.AsQueryable();
            if (!string.IsNullOrEmpty(Pesquisar))
                q = q.Where(c => c.Nome.Contains(Pesquisar));
            q = q.OrderBy(c => c.Nome);

            return View(q.ToList());
        }
        public ActionResult SimpleSearch(DateTime? minDate, DateTime? maxDate)
        {
            if (!minDate.HasValue)
            {
                minDate = new DateTime(DateTime.Now.Year, 1, 1);
            }
            if (!maxDate.HasValue)
            {
                maxDate = DateTime.Now;
            }
            ViewData["minDate"] = minDate.Value.ToString("yyyy-MM-dd");
            ViewData["maxDate"] = maxDate.Value.ToString("yyyy-MM-dd");
            var result = _contexto.Clientes.FindAsync(minDate, maxDate);
            return View(result);
        }
        [HttpPost]
        public ActionResult Index(string recebeNome, int recebeOpcao)
        {
            try
            {
                ClientesModel dao = new ClientesModel();
                IQueryable<BancoContext> sql;
                sql = null;

                if (recebeOpcao == 1)
                {
                    var q = _contexto.Clientes.AsQueryable();
                    if (!string.IsNullOrEmpty(recebeNome))
                        q = q.Where(c => c.Tipo.ToString().Contains(recebeNome));
                    q = q.OrderBy(c => c.Tipo);
                  
                    TempData["opcao1"] = "cancelado";
                }
                return View(sql.ToList());
                if (recebeOpcao == 2)
                {
                    var q = _contexto.Clientes.AsQueryable();
                    if (!string.IsNullOrEmpty(recebeNome))
                        q = q.Where(c => c.Tipo.ToString().Contains(recebeNome));
                    q = q.OrderBy(c => c.Tipo);

                    TempData["opcao2"] = "bloqueado";
                }
                return View(sql.ToList());

                if (recebeOpcao == 3)
                {
                    var q = _contexto.Clientes.AsQueryable();
                    if (!string.IsNullOrEmpty(recebeNome))
                        q = q.Where(c => c.Tipo.ToString().Contains(recebeNome));
                    q = q.OrderBy(c => c.Tipo);

                    TempData["opcao3"] = "padrao";
                }

                return View(sql.ToList());

            }
            catch (Exception ex)
            {
                TempData["Erro"] = "Erro na gravação dos dados " + ex.Message;
            }
            return View();

        }
        [HttpGet]
        public IActionResult CriarCliente()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> CriarCliente(ClientesModel clientes)
        {
            if (ModelState.IsValid)
            {
                _contexto.Add(clientes);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else return View(clientes);

            List<SelectListItem> items = new List<SelectListItem>();

            items.Add(new SelectListItem { Text = "Padrao", Value = "0" });

            items.Add(new SelectListItem { Text = "Bloqueado", Value = "1" });

            items.Add(new SelectListItem { Text = "Cancelado", Value = "2", Selected = true });

            ViewBag.MovieType = items;

            return View(clientes.Tipo);
        }
        [HttpGet]
        public IActionResult EditarCliente(int? id)
        {
            if (id != null)
            {
                ClientesModel clientes = _contexto.Clientes.Find(id);
                return View(clientes);
            }
            else return NotFound();           
        }
        [HttpPost]
        public async Task<IActionResult> EditarCliente(int id, ClientesModel clientes)
        {
            if (id != null)
            {
                if (ModelState.IsValid)
                {
                    _contexto.Update(clientes);
                    await _contexto.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
                else return View(clientes);

            }
            else return NotFound();
        }
        [HttpGet]
        public IActionResult ExcluirCliente(int? id)
        {
            if (id != null)
            {
                ClientesModel clientes = _contexto.Clientes.Find(id);
                return View(clientes);
            }
            else return NotFound();
        }
        [HttpPost]
        public async Task<IActionResult> ExcluirCliente(int id, ClientesModel clientes)
        {
            if (id != null)
            {
                _contexto.Remove(clientes);
                await _contexto.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            else return NotFound();
        }
        [HttpGet]
        public async Task<int> Get(int cont)
        {
            var contador = _contexto.Update(cont);

            return cont;
        }


        [HttpPost]
        public async Task Post(int cont)
        {
            var contador = _contexto.Update(cont);
            await contador.GetDatabaseValuesAsync();
        }
        
    }
}

CadastroDeClientes/Controllers/HomeController.cs
using CadastroDeClientes.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace CadastroDeClientes.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CadastroDeClientes/Views/Clientes/CriarCliente.cshtml
@model CadastroDeClientes.Models.ClientesModel

@{
    ViewData["Title"] = "CriarCliente";
}

<h1>Cadastrar Pessoal</h1>

<h4>Pessoa</h4>
<hr />
<div class="row">
    <div class="col-md-12">
        <form asp-action="CriarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>

            <div class="form-row">

                <div class="form-group col-6">
                    <label asp-for="Nome" class="control-label"></label>
                    <input asp-for="Nome" class="form-control" />
                    <span asp-validation-for="Nome" class="text-danger"></span>
                </div>
                <div class="form-group col-6">
                    <label asp-for="Cpf" class="control-label"></label>
                    <input asp-for="Cpf" class="form-control cpf" name="Cpf" id="Cpf" />
                    <span asp-validation-for="Cpf" class="text-danger"></span>
                </div>

            </div>
            <div class="form-row">
                <div class="form-group col-6">
                    <label asp-for="DataNascimento" class="control-label"></label>
                    <input asp-for="DataNascimento" type="date" class="form-control" />
                    <span asp-validation-for="DataNascimento" class="text-danger"></span>
                </div>
                <div class="form-group col-2">
                    <div class="form-check">
                        <input asp-for="Tipo" name="recebeOpcao" value="cancelado" class="form-check-input" type="radio" id="flexRadioDefault2" checked>
                        <label class="form-check-label" for="flexRadioDefault2">
                            Padrão
                        </label>
        </div>
    </div>
    <div class="form-group col-2">
        <div class="form-check">
            <input asp-for="Tipo" name="recebeOpcao" value="bloqueado" class="form-check-input" type="radio" id="flexRadioDefault1">
                        <label class="form-check-label" for="flexRadioDefault1">
                            Bloqueado
                        </label>
                    </div>
                </div>
                <div class="form-group col-2">
                    <div class="form-check">
                        <input asp-for="Tipo" name="recebeOpcao" value="padrao" class="form-check-input" type="radio" id="flexRadioDefault0">
                            <label class="form-check-label" for="flexRadioDefault2">
                                Cancelado
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <input type="submit" value="Criar" class="btn btn-primary" />
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="Index">Voltar para Lista</a>
    </div>

    @section Scripts {
        @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}

    }

CadastroDeClientes/Views/Clientes/EditarCliente.cshtml
@model CadastroDeClientes.Models.ClientesModel

@{
    ViewData["Title"] = "EditarCliente";
}

<h1>Editar Cadastro de Cliente</h1>

<h4>ClientesWeb</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditarCliente">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DataNascimento" class="control-label"></label>
                <input asp-for="DataNascimento" type="date" class="form-control" />
                <span asp-validation-for="DataNascimento" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Tipo" class="control-label"></label>
                <input asp-for="Tipo" class="form-control" />
                <span asp-validation-for="Tipo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para Lista</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CadastroDeClientes/Views/Clientes/ExcluirCliente.cshtml
@model CadastroDeClientes.Models.ClientesModel

@{
    ViewData["Title"] = "ExcluirCliente";
}

<h1>ExcluirCliente</h1>

<h3>Tem certeza de que deseja excluir?</h3>
<div>
    <h4>ClientesWeb</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DataNascimento)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DataNascimento)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Tipo)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Tipo)
        </dd>
    </dl>
    
    <form asp-action="ExcluirCliente">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Voltar para Lista</a>
    </form>
</div>

CadastroDeClientes/Views/Clientes/Index.cshtml
@model IEnumerable<CadastroDeClientes.Models.ClientesModel>

@{
    ViewData["Title"] = "Index";
}

<h1>Início cadastro</h1>

<p>
    <a asp-action="CriarCliente">Cadastrar novo cliente</a>
</p>
<div class="container-fluid">
    <div class="row">
        <div class="col-4">
            <div class="bg-success border rounded text-white">
                <h5>Padrão</h5>
                <br />
                <h2 id="countValor" value="padrao">0</h2>
            </div>
        </div>
        <div class="col-4">
            <div class="bg-warning border rounded text-white">
                <h5>Bloqueado</h5>
                <br />
                <h2 id="countValor" value="bloqueado">0</h2>
            </div>
        </div>
        <div class="col-4">
            <div class="bg-danger border rounded text-white">
                <h5>Cancelado</h5>
                <br />
                <h2 id="countValor" value="cancelado">0</h2>
            </div>
        </div>
    </div>
</div>

<br />
<p>
    Filtros para Pesquisa:
    @using (Html.BeginForm("Index", "Clientes", FormMethod.Get))
    {
        <form>
            <div class="form-group">
                @Html.TextBox("Pesquisar")
               
                    <label for="minDate">Data Inicial</label>
                    <input type="date" value="dataAn" name="minDate" />
                    <label for="minDate">Data Final</label>
                    <input type="date" value="dataAn" name="maxDate" />
            </div>
            <input type="submit" placeholder="Nome" value="Pesquisar" />
        </form>
    }


</p>
<table class="table">
    <thead>

        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Nome)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Cpf)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DataNascimento)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Tipo)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
                    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Cpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DataNascimento)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Tipo)
            </td>
            <td>
                <a asp-action="EditarCliente" asp-route-id="@item.Id">Editar</a> |
                <a asp-action="ExcluirCliente" asp-route-id="@item.Id">Excluir</a>
            </td>
        </tr>
    }
    </tbody>
</table>

CadastroDeClientes/Views/Clientes/PesquisaCliente.cshtml
@model CadastroDeClientes.Models.ClientesModel
@{

    ViewData["Title"] = "PesquisaCliente";
}
<p>
    <a asp-action="Create">Create New</a>
</p>

<form asp-controller="Clientes" asp-action="PesquisaCliente">
    <p>
        Title: <input type="text" name="SearchString" />
        <input type="submit" value="Pesquisar" />
    </p>
</form>

CadastroDeClientes/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Bem vindo!</h1>
</div>

CadastroDeClientes/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CadastroDeClientes</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CadastroDeClientes</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Página Inicial</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Clientes" asp-action="Index">Clientes</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - CadastroDeClientes<a asp-area="" asp-controller="Home" asp-action="Privacy"></a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>